# Generated by Django 3.2.3 on 2021-09-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('M', 'Maths'), ('S', 'Science'), ('E', 'English')], max_length=2)),
                ('question', models.CharField(max_length=200)),
                ('a', models.CharField(max_length=100)),
                ('b', models.CharField(max_length=100)),
                ('c', models.CharField(max_length=100)),
                ('d', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=1)),
            ],
        ),
    ]
