# Generated by Django 3.2.3 on 2021-09-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=20)),
                ('marks', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='quiz',
            name='subject',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Science', 'Science'), ('English', 'English')], max_length=20),
        ),
    ]
