# Generated by Django 3.2.3 on 2021-09-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210911_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='result',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
